---
- name: 
  hosts: all
  become: true
  vars:
    docker_users:
      - panda
      - vagrant
    docker_daemon_options:
      insecure-registries : ["192.168.44.44:8082"]
  roles:
    - user
    - packages
    - geerlingguy.docker
    - christiangda.awscli
    - christiangda.awscli_configure
    - diodonfrost.terraform