---
- name: clone roles
  hosts: all
  become: true
  vars:
    git_repository: https://github.com/snuuffy/Ansible_roles.git
    git_branch: "main"
    docker_daemon_options:
      insecure-registries : ["192.168.44.44:8082"]


  tasks:
  - name: Create directory
    file:
      path: /etc/ansible/roles
      state: directory
      mode: '0755'
        
  - name: Checkout
    git:
      repo: "{{ git_repository }}"
      dest: "/etc/ansible/roles"
      version: "{{ git_branch }}"